fix: add greenhouse proxy
fingerprintjs/fingerprint.com pull request #1289
Opened 2023-05-03 19:14 UTC by natapg

2023-05-03 20:01 UTC, natapg commented on src/helpers/api.ts
> +  if (!IS_PRODUCTION) {
just for testing, revert before merge

2023-05-04 18:00 UTC, dcorso21 requested changes

2023-05-04 18:00 UTC, dcorso21 commented on src/helpers/api.ts
> +  if (!IS_PRODUCTION) {
I'll wait for this to be reverted before approval just to be sure.

2023-05-04 18:05 UTC, dcorso21 approved these changes

2023-05-04 18:14 UTC, merged